# Ansible Playbook to configure the core switch using send_config.py

- name: Configure the core switch
  hosts: switch_console
  connection: local
  gather_facts: false

  vars:
    switch_commands:
    - command: enable
      expect: ''
    - command: configure terminal
      expect: Enter configuration commands, one per line.  End with CNTL/Z.
## Configure basic settings
    - command: hostname switch
      expect: ''
    - command: ip domain-name indef.space
      expect: ''
## Configure console authentication
    - command: username {{ admin_username}} privilege 15 secret {{ admin_password }}
      expect: ''
    - command: line console 0
      expect: ''
    - command: login local
      expect: ''
    - command: exec-timeout 5 0
      expect: ''
## Disable unnecessary services
    - command: no ip http server
      expect: ''
    - command: no cdp run
      expect: ''
    - command: no lldp run
      expect: ''
## Configure the banner
    - command: banner login ^
      expect: ''
    - command: indef.space Lab Switch\nUNAUTHORIZED ACCESS PROHIBITED\n^
      expect: ''
    - command: end
      expect: ''
## Save running configuration
    - command: write memory
      expect: Building configuration...

  tasks:
  - name: Write Commands to JSON
    copy:
      content: "{{ switch_commands | to_nice_json }}"
      dest: /tmp/switch_commands.json

  - name: Send configs to switch
    command: >
      python3 {{ playbook_dir }}/send_config.py
      /dev/ttyUSB0
      9600
      /tmp/switch_commands.json
