# An example playbook for working with send_config.py

- name: Test the send_config.py script
  hosts: switch_console
  connection: local
  gather_facts: false

  vars:
    switch_commands:
    - command: enable
      expect: ''
    - command: configure terminal
      expect: Enter configuration commands, one per line.  End with CNTL/Z.
    - command: hostname switch
      expect: ''
    - command: end
      expect: switch#
    - command: exit
      expect: switch con0 is now available

  tasks:
  - name: Write Commands to JSON
    copy:
      content: "{{ switch_commands | to_nice_json }}"
      dest: /tmp/switch_commands.json

  - name: Send configs to switch
    command: >
      python3 {{ playbook_dir }}/send_config.py
      /dev/ttyUSB0
      9600
      /tmp/switch_commands.json
