# Installs and makes available the DHCP service
- name: install DHCP feature
  ansible.windows.win_feature:
    name: DHCP
    state: present
    include_management_tools: yes
  register: win_feature

- name: reboot if required
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: load creds
  ansible.builtin.include_vars:
    file: "../inventories/{{ site.segment }}/identity/group_vars/all/vault.yml"
  no_log: true
  run_once: true

- name: load accounts
  ansible.builtin.include_vars:
    file: "../inventories/{{ site.segment }}/identity/group_vars/identity_authority/accounts.yml"
  run_once: true
  no_log: true

- name: set creds for DC connection
  delegate_to: "{{ (dcs.primary.hostname | split('.'))[0] }}"
  ansible.builtin.set_fact:
    ansible_user: "{{ accounts[2].username }}"
    ansible_password: "{{ credentials[accounts[2].username] }}"
    ansible_winrm_transport: "kerberos"
#    dhcp_hostname: "{{ inventory_hostname }}.{{ domain.sub }}.{{ domain.root }}"
#    dhcp_ip: "{{ ip }}"
  no_log: true
  delegate_facts: true

- name: authorize DHCP in AD
  delegate_to: "{{ (dcs.primary.hostname | split('.'))[0] }}"
  ansible.windows.win_powershell:
    script: "Add-DhcpServerInDC -DnsName '{{ inventory_hostname }}.{{ domain.sub }}.{{ domain.root }}' -IPAddress {{ ip }}"
  changed_when: false

- name: reset creds
  ansible.builtin.set_fact:
    ansible_user: "andhcp01"
    ansible_password: "{{ credentials['andhcp01'] }}"
    ansible_connection: "winrm"
    ansible_winrm_scheme: "https"
    ansible_winrm_transport: "ntlm"
  no_log: true

- name: test connection
  ansible.builtin.win_ping:

- name: verify DHCP status
  ansible.windows.win_powershell:
    script: |
      Start-Sleep -Seconds 5
      $service = Get-Service DHCPServer
      @{ status = $service; ready = $service.Status -eq "Running" }
  register: output
  changed_when: false
  failed_when: not output.output[0].ready
