# Merges a provided control plane specification with the selected cluster variables
- name: check variables
  ansible.builtin.assert:
    that:
    - control_plane_config is defined
    - control_plane_config is sequence
    - control_plane_config | length == 2
    - target is defined
    - target is mapping

- name: set hostname
  ansible.builtin.set_fact:
    updated_hostname_doc: "{{ control_plane_config[1] | combine({'hostname': target.hostname}) | dict2items | rejectattr('key','equalto','auto') | items2dict}}"
    updated_main_doc: "{{ control_plane_config[0]}}"

- name: set cert SANs
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {'machine':
            {'certSANs': [
              target.fqdn,
              target.hostname,
              target.ip.service,
              target.ip.storage
            ]}
          }, recursive=True)
      }}

- name: set data node taint
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {'machine':
            {'nodeTaints':
              {
                'node-class': target.taint + ':NoSchedule'
              }
            }
          },
        recursive=True)
      }}

- name: set machine network settings
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {'machine':
            {'network':
              {
                'interfaces':
                [
                  {
                    'interface': 'ens18',
                    'addresses':
                    [
                      target.ip.service_cidr,
                    ],
                    'routes':
                    [
                      {
                        'network': '0.0.0.0/0',
                        'gateway': vlans.core.gateway
                      }
                    ]
                  },
                  {
                    'interface': 'ens19',
                    'addresses': 
                    [
                      target.ip.storage_cidr
                    ],
                    'routes': []
                  }
                ],
                'nameservers':
                [
                  components.identity.rodcs.ip,
                  components.identity.rwdcs.ip[0]
                ]
              }
            }
          },
        recursive=True)
      }}

- name: set cluster network settings
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {
            'cluster':
            {
              'network':
              {
                'podSubnets': [components.talos.primary_cluster.pod_subnet],
                'serviceSubnets': [components.talos.primary_cluster.service_subnet]
              }
            }
          },
          recursive=True
        )
      }}

- name: set cilium CNI
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {
            'cluster':
            {
              'network':
              {
                'cni':
                  {
                    'name': 'none'
                  }
              },
              'proxy':
              {
                'disabled': true
              }
            }
          },
          recursive=True
        )
      }}

- name: set machine sysctls for network
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine(
          {
            'machine':
            {
              'sysctls':
              {
                'net.ipv6.conf.all.disable_ipv6': '1'
              }
            }
          },
          recursive=True
        )
      }}

- name: set ntp sources
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine
        (
          {
            'machine':
            {
              'time':
              {
                'servers':
                [
                  components.identity.rodcs.ip,
                  components.identity.rwdcs.ip[0]
                ]
              }
            }
          },
          recursive=True
        )
      }}


# Talos doesn't accept octal notation for permissions
## decimal 420 = octal 0644
- name: set IQN
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine
        (
          {
            'machine':
            {
              'files':
              [
                {
                  'path': '/etc/iscsi/initiatorname.iscsi',
                  'permissions': 0o644,
                  'op': 'overwrite',
                  'content': "InitiatorName=iqn.2025-07.space.indef.ops:" ~ components.talos.primary_cluster.cluster_name ~ "-" ~ target.hostname
                }
              ]
            }
          },
          recursive=True
        )
      }}

- name: set image to schematic
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine
        (
          {
            'machine':
            {
              'install':
              {
                'image': "factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac:v1.12.5"
              }
            }
          },
          recursive=True
        )
      }}

## TODO - replace with root CA cert once available
- name: trust gitlab self-signed cert
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine
        (
          {
            'machine':
            {
              'registries':
              {
                'config':
                {
                  gitlab_registry:
                  {
                    'tls':
                    {
                      'ca': lookup('file',role_path ~ '/files/gitlab.crt') | b64encode
                    }
                  }
                }
              }
            }
          },
          recursive=True
        )
      }}

- name: enable talos host-dns service
  ansible.builtin.set_fact:
    updated_main_doc: |
      {{
        updated_main_doc | combine
        (
          {
            'machine':
            {
              'features':
              {
                'hostDNS':
                {
                  'enabled': true,
                  'forwardKubeDNSToHost': true
                }
              }
            }
          },
          recursive=True
        )
      }}

- name: build new config
  become: true
  ansible.builtin.copy:
    content: "{{ [updated_main_doc,updated_hostname_doc] | map('to_nice_yaml') | join('---\n') }}"
    dest: "{{ k8s_root }}/{{ target.hostname }}.yaml"
    owner: root
    group: ansible
    mode: 0750

- name: validate config
  changed_when: false
  ansible.builtin.command: "talosctl validate --config {{ k8s_root }}/{{ target.hostname }}.yaml --mode metal"
  register: validate_result

- name: fail if invalid
  ansible.builtin.assert:
    that:
    - validate_result.rc == 0