# Deploys secrets for the Observer application
- name: create secret for root cert
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-root-cert
        namespace: "{{ item.namespace }}"
      stringData:
        root.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_root.crt')}}"

- name: create secret for wcladapter material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-db-certs-wcladapter
        namespace: "{{ item.namespace }}"
      stringData:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_wcladapter.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_wcladapter.key')}}"

- name: create secret for evaluation engine material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-db-certs-evaluation
        namespace: "{{ item.namespace }}"
      stringData:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_evengine.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_evengine.key')}}"

- name: create secret for factors material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-db-certs-factors
        namespace: "{{ item.namespace }}"
      stringData:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_factors.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_factors.key')}}"

- name: create secret for postgres material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-db-certs-postgres
        namespace: "{{ item.namespace }}"
      stringData:
        server.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_postgres.crt')}}"
        server.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_postgres.key')}}"

- name: load credentials
  run_once: true
  ansible.builtin.include_vars:
    file: "../inventories/{{ site.segment }}/identity/group_vars/all/vault.yml"
  no_log: true

- name: create secret for postgres superuser password
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-postgres-superuser
        namespace: "{{ item.namespace }}"
      stringData:
        superuser_pass: "{{ observer.postgres.superuser | selectattr('namespace', 'equalto', item.namespace) | map(attribute='password') | first }}"

- name: create secret for image pulls from local gitlab
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ops-indef-container-reg
        namespace: "{{ item.namespace }}"
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: >-
          {{
            {
              'auths': {
                observer.image_pull.registry: {
                  'username': observer.image_pull.username,
                  'password': observer.image_pull.token,
                  'auth': (observer.image_pull.username + ':' + observer.image_pull.token) | b64encode
                }
              }
            } | to_json
          }}
