# Deploys secrets for the Observer application
- name: create secret for root cert
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer-root-cert
        namespace: "{{ item.namespace }}"
      data:
        root.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_root.crt')}}"

- name: create secret for wcladapter material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer_db_certs_wcladapter
        namespace: "{{ item.namespace }}"
      data:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_wcladapter.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_wcladapter.key')}}"

- name: create secret for evaluation engine material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer_db_certs_wcladapter
        namespace: "{{ item.namespace }}"
      data:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_evengine.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_evengine.key')}}"

- name: create secret for factors material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer_db_certs_wcladapter
        namespace: "{{ item.namespace }}"
      data:
        client.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_factors.crt')}}"
        client.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_factors.key')}}"

- name: create secret for postgres material
  loop: "{{ observer_instances }}"
  loop_control:
    label: "Creating secret in {{item.namespace}}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: observer_db_certs_wcladapter
        namespace: "{{ item.namespace }}"
      data:
        server.crt: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_postgres.crt')}}"
        server.key: "{{ lookup('file',role_path ~ '/files/' ~ item.namespace ~ '/observer_postgres.key')}}"