# Enforces VM hardware configuration

- name: configure hardware specs
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: bootstrap
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    description: "{{ vm_description }}"
    state: present
    sockets: "{{ vm_sockets }}"
    cores: "{{ vm_cores }}"
    memory: "{{ vm_mem }}"
    balloon: 0
    scsihw: virtio-scsi-pci
    update: true
  changed_when: false

- name: configure os disk
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_disk:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ vm_id }}"
    disk: scsi0
    state: present
    storage: "{{ template_storage }}"
    size: "{{ template_storage_size }}"

- name: configure data disk
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_disk:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ vm_id }}"
    disk: scsi1
    state: present
    storage: "{{ vm_storage }}"
    size: "{{ vm_storage_size }}"

- name: configure nic
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_nic:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ vm_id }}"
    interface: net0
    bridge: "vmbr{{ bridges.data_bridge }}"
    tag: "{{ vm_vid }}"

