# Enforces VM hardware configuration

- name: configure hardware specs
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ hypervisor_target }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    description: "{{ vm_description }}"
    state: present
    sockets: "{{ vm_sockets }}"
    cores: "{{ vm_cores }}"
    memory: "{{ vm_mem }}"
    balloon: 0
    scsihw: virtio-scsi-pci
    update: true
  changed_when: false

- name: configure disks for clone
  when: 'template_storage is defined'
  block:
  - name: configure os disk (template)
    delegate_to: localhost
    vars:
      ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
    community.proxmox.proxmox_disk:
      api_host: "{{ ansible_host }}"
      api_user: "{{ api_username }}"
      api_token_id: "{{ api_token_name }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ vm_id }}"
      disk: scsi0
      state: present
      storage: "{{ template_storage }}"
      size: "{{ template_storage_size }}"

  - name: configure data disk (template)
    when: vm_storage_size is defined
    delegate_to: localhost
    vars:
      ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
    community.proxmox.proxmox_disk:
      api_host: "{{ ansible_host }}"
      api_user: "{{ api_username }}"
      api_token_id: "{{ api_token_name }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ vm_id }}"
      disk: scsi1
      state: present
      storage: "{{ vm_storage | default(omit) }}"
      size: "{{ vm_storage_size | default(omit) }}"

- name: configure disks for new
  when: 'template_storage is not defined'
  block:
  - name: configure os disk (fresh)
    delegate_to: localhost
    vars:
      ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
    community.proxmox.proxmox_disk:
      api_host: "{{ ansible_host }}"
      api_user: "{{ api_username }}"
      api_token_id: "{{ api_token_name }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ vm_id }}"
      disk: scsi0
      state: present
      storage: "{{ vm_storage | default(omit) }}"
      size: "{{ vm_storage_size | default(omit) }}"
      cache: "{{ vm_storage_cache }}"

- name: configure nic
  delegate_to: localhost
  loop: "{{ [vm_vid] | flatten }}"
  loop_control:
    loop_var: item
    index_var: idx
    label: "Configuring NIC{{ idx }} with VLAN {{ item }}"
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_nic:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ vm_id }}"
    interface: "net{{ idx }}"
    bridge: "vmbr{{ bridges.data_bridge }}"
    tag: "{{ item | default(omit) }}"

- name: configure dedicated mgmt vlan nic
  when: vm_vid is undefined
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_nic:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ vm_id }}"
    interface: "net{{ ([vm_id] | flatten | length) + 1 }}"
    bridge: "vmbr{{ bridges.mgmt_bridge }}"
