# Creates a VM that doesn't exist and applies an ISO for OS install
#- name: verify defined vars
#  ansible.builtin.fail:
#    msg: "Variable {{ item }} is not defined"
#  loop:
#  -
#  when: vars[item] is undefined

- name: create vm
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ mgmt_pi_ansible_python }}"
  community.proxmox.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ api_username }}"
    api_token_id: "{{ api_token_name }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ hypervisor_target }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    full: true
    storage: "{{ vm_storage }}"
    state: present
    timeout: 600