- name: render caddy configuration
  become: true
  ansible.builtin.template:
    src: templates/caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: 0750
    owner: root
    group: caddy
  register: config

- name: reload caddy
  become: true
  when: config.changed
  ansible.builtin.systemd_service:
    name: caddy
    state: reloaded
    enabled: true