- name: setup log files
  become: true
  loop: "{{ monitored_paths | selectattr('path','search','/var/log/caddy') }}"
  loop_control:
    label: "Touching {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: caddy
    group: caddy
    mode: 0644
    state: file

- name: render caddy configuration
  become: true
  ansible.builtin.template:
    src: templates/caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: 0750
    owner: root
    group: caddy
  register: config

- name: reload caddy
  become: true
  when: config.changed
  ansible.builtin.systemd_service:
    name: caddy
    state: reloaded
    enabled: true