# RWDC Variables

#############
## ANSIBLE ##
#############

ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_scheme: https
ansible_port: 5986
ansible_winrm_server_cert_validation: ignore
ansible_user: ".\\ansible"

############
## DOMAIN ##
############

# Domain Root: 
ou_tree:
## Infrastructure Branch
- path: "OU=Servers,DC=ops,DC=indef,DC=space"
  protect: true
- path: "OU=Linux,OU=Servers,DC=ops,DC=indef,DC=space"
- path: "OU=Windows,OU=Servers,DC=ops,DC=indef,DC=space"
- path: "OU=Workstations,DC=ops,DC=indef,DC=space"
  protect: true
- path: "OU=Linux,OU=Workstations,DC=ops,DC=indef,DC=space"
- path: "OU=Windows,OU=Workstations,DC=ops,DC=indef,DC=space"
- path: "OU=Network,DC=ops,DC=indef,DC=space"
- path: "OU=Junos,OU=Network,DC=ops,DC=indef,DC=space"
- path: "OU=Linux,OU=Network,DC=ops,DC=indef,DC=space"
## Identities Branch
- path: "OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Privileged-Users,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Regular-Users,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Service-Accounts,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=gMSAs,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Privileged-Groups,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Access-Groups,OU=Identities,DC=ops,DC=indef,DC=space"
## Policies Branch
- path: "OU=Windows-Anchor,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Linux-Anchor,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Junos-Anchor,OU=Identities,DC=ops,DC=indef,DC=space"
- path: "OU=Users-Anchor,OU=Identities,DC=ops,DC=indef,DC=space"

groups:
## Admin Groups
- name: "Server Admins"
  scope: "Global"
  type: "Security"
  ou: "OU=Privileged-Groups,OU=Identities,DC=ops,DC=indef,DC=space"

sites:
- name: "Core-Protected"
- name: "Core"

site-links:
- name: Core-Internal
  sites: ["Core-Protected","Core"]
  cost: 100

subnets:
- cidr: "10.0.21.0/24"
  site: "Core-Protected"
- cidr: "10.0.20.0/24"
  site: "Core"
- cidr: "10.0.99.0/24"
  site: "Core"
