# Configures the switch for use in the lab environment

- name: check connection type
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: check connection type
    debug:
      var: ansible_connection

- name: Ensure manual configs were applied correctly
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: Set hostname and domain
    cisco.ios.ios_config:
      lines:
      - hostname switch
      - ip domain-name indef.space
  - name: Enable SSH and login local
    cisco.ios.ios_config:
      lines:
      - ip ssh version 2
      - line vty 0 4
      - login local
      - transport input ssh
  - name: Create management VLAN
    cisco.ios.ios_config:
      lines:
      - vlan 99
      - name Management
  - name: Set interface VLAN 99
    cisco.ios.ios_config:
      lines:
      - interface vlan 99
      - ip address 10.0.99.10 255.255.255.0
      - no shutdown
  - name: save config
    cisco.ios.ios_config:
      save_when: modified

- name: Secure the management SVI
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: Create MGMT_ONLY ACL
    cisco.ios.ios_config:
      lines:
      - ip access-list standard MGMT_ONLY
      - permit 10.0.99.0 0.0.0.255
      - deny any
  - name: Apply MGMT_ONLY ACL to VLAN99 Interface
    cisco.ios.ios_config:
      lines:
      - line vty 0 4
      - access-class MGMT_ONLY in

- name: Create the VLANs and interfaces
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: Create core VLAN
    cisco.ios.ios_config:
      lines:
      - vlan 20
      - name Core

  - name: Create user VLAN
    cisco.ios.ios_config:
      lines:
      - vlan 40
      - name User

  - name: Create DMZ VLAN
    cisco.ios.ios_config:
      lines:
      - vlan 30
      - name DMZ

  - name: Create External VLAN
    cisco.ios.ios_config:
      lines:
      - vlan 10
      - name External

- name: Configure access and trunk ports
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: Configure iDRAC ports
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/45
      - description Server1 iDRAC
      - switchport mode access
      - switchport access vlan 99
      - no shutdown
      - interface gigabitEthernet 1/47
      - description Server2 iDRAC
      - switchport mode access
      - switchport access vlan 99
      - no shutdown

  - name: Configure Compute NIC ports
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/27
      - description Server1 NIC4
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/29
      - description Server1 NIC3
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/31
      - description Server1 NIC2
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/33
      - description Server1 NIC1
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/35
      - description Server2 NIC4
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/37
      - description Server2 NIC3
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/39
      - description Server2 NIC2
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown
      - interface gigabitEthernet 1/41
      - description Server2 NIC1
      - switchport mode trunk
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan 10,20,30,40
      - no shutdown

  - name: Configure WAP port
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/21
      - description WAP
      - switchport mode access
      - switchport access vlan 40
      - no shutdown


  - name: Configure Router port
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/19
      - description External Router
      - switchport mode access
      - switchport access vlan 10
      - no shutdown

  - name: Configure Tower ports
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/1
      - description James Tower
      - switchport mode access
      - switchport access vlan 40
      - no shutdown
      - interface gigabitEthernet 1/3
      - description Vix Tower
      - switchport mode access
      - switchport access vlan 40
      - no shutdown

  - name: Configure Vault port
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/17
      - description Vault Pi
      - switchport mode access
      - switchport access vlan 20
      - no shutdown

  - name: Disable unused ports
    cisco.ios.ios_config:
      lines:
      - interface gigabitEthernet 1/2, 1/4, 1/5, 1/6
      - description ** DISABLED **
      - shutdown
      - interface gigabitEthernet 1/16, 1/18, 1/20, 1/22
      - description ** DISABLED **
      - shutdown
      - interface gigabitEthernet 1/23-26
      - description ** DISABLED **
      - shutdown
      - interface gigabitEthernet 1/28, 1/30, 1/32, 1/34, 1/36, 1/38, 1/40, 1/42
      - description ** DISABLED **
      - shutdown
      - interface gigabitEthernet 1/43-44, 1/46, 1/48
      - description ** DISABLED **
      - shutdown
