# Playbook to configure access switches
- hosts: access_switches
  gather_facts: false

  pre_tasks:
  - name: connection check
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: ciscosmb_check.yml
    tags: ["always"]

  - meta: reset_connection

  - name: terminal config
    cisco.ios.ios_command:
      commands:
      - terminal datadump
    tags: ["always"]

  tasks:

  - name: configure ssh
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: ciscosmb.yml
    tags: ["baseline","ssh"]

  - name: apply baseline configs
    ansible.builtin.import_role:
      name: infrastructure/ciscosmb
      tasks_from: baseline.yml
    tags: ["baseline","ssh"]

  - name: apply vlan configs
    ansible.builtin.import_role:
      name: infrastructure/ciscosmb
      tasks_from: vlans.yml
    tags: ["service","vlans"]

  - name: apply interface configs
    ansible.builtin.import_role:
      name: infrastructure/ciscosmb
      tasks_from: interfaces.yml
    tags: ["service","ints"]

  - debug:
      msg: "Issue `copy run start` on the host directly if there were any changes"
    tags: ["always"]
