- hosts: compute_nodes
  serial: 1
  gather_facts: false

  tasks:
  - name: probe for connection status
    tags: ["always"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux_check.yml

- hosts: compute_nodes
  gather_facts: false

  tasks:

# Baseline
  - name: Configure host networking
    become: true
    tags: ["baseline","net"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: proxmox_network.yml

  - name: configure proxmox host
    tags: ["baseline","proxmox"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: proxmox.yml

  - name: apply linux baseline
    tags: ["baseline","host"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: linux.yml

  - name: Configure SSH
    tags: ["baseline","ssh"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux.yml
