- hosts: compute_nodes
  serial: 1
  gather_facts: false

  tasks:
  - name: probe for connection status
    tags: ["always"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux_check.yml

- hosts: compute_nodes
  gather_facts: false

  tasks:

# Baseline
  - name: Configure host networking
    become: true
    tags: ["baseline","net"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: proxmox_network.yml

  - name: configure proxmox host
    tags: ["baseline","proxmox"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: proxmox.yml

  - name: apply linux baseline
    tags: ["baseline","host"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: linux.yml

  - name: Configure SSH
    tags: ["baseline","ssh"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux.yml

# Infrastructure VMs
  - name: create vFW VMs
    tags: ["vms","network","vfw","network/vfw"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","network","vfw","network/vfw"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(vfw.vm.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating vFW on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.alma9.name }}"
      template_id: "{{ templates.alma9.id }}"
      template_storage: "{{ templates.alma9.storage.type }}"
      template_storage_size: "{{ templates.alma9.storage.size }}"
      vm_name: "{{ vfw.vm.name[iteration] }}"
      vm_id: "{{ vfw.vm.id[iteration] }}"
      vm_description: "{{ vfw.vm.description[iteration] }}"
      vm_storage: "{{ vfw.vm.storage }}"
      vm_sockets: "{{ vfw.vm.sockets }}"
      vm_cores: "{{ vfw.vm.cores }}"
      vm_mem: "{{ vfw.vm.mem }}"
      ## To configure the service, see playbooks/vfw.yml

  - name: create DHCP VMs
    tags: ["vms","services","dhcp","service/dhcp"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","services","dhcp","service/dhcp"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(dhcp.vm.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating DHCP Server on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.win22.name }}"
      template_id: "{{ templates.win22.id }}"
      template_storage: "{{ templates.win22.storage.type }}"
      template_storage_size: "{{ templates.win22.storage.size }}"
      vm_name: "{{ dhcp.vm.name[iteration] }}"
      vm_id: "{{ dhcp.vm.id[iteration] }}"
      vm_description: "{{ dhcp.vm.description[iteration] }}"
      vm_storage: "{{ dhcp.vm.storage }}"
      vm_sockets: "{{ dhcp.vm.sockets }}"
      vm_cores: "{{ dhcp.vm.cores }}"
      vm_mem: "{{ dhcp.vm.mem }}"
      vm_vid: "{{ dhcp.vm.vid }}"
      ## To configure the service, see playbooks/dhcp.yml

  - name: create RODC VMs
    tags: ["vms","services","ad","services/ad"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","services","ad","services/ad"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(rodc.vm.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating RODC Server on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.win22.name }}"
      template_id: "{{ templates.win22.id }}"
      template_storage: "{{ templates.win22.storage.type }}"
      template_storage_size: "{{ templates.win22.storage.size }}"
      vm_name: "{{ rodc.vm.name[iteration] }}"
      vm_id: "{{ rodc.vm.id[iteration] }}"
      vm_description: "{{ rodc.vm.description[iteration] }}"
      vm_storage: "{{ rodc.vm.storage }}"
      vm_storage_size: "{{ rodc.vm.size }}"
      vm_sockets: "{{ rodc.vm.sockets }}"
      vm_cores: "{{ rodc.vm.cores }}"
      vm_mem: "{{ rodc.vm.mem }}"
      vm_vid: "{{ rodc.vm.vid }}"
      ## To configure the service, see playbooks/domain.yml

  - name: create Code/GitLab subsystem VMs
    tags: ["vms","services","code","gitlab","services/gitlab"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","services","code","gitlab","services/gitlab"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(code.glab.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating Code VM on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.alma9.name }}"
      template_id: "{{ templates.alma9.id }}"
      template_storage: "{{ templates.alma9.storage.type }}"
      template_storage_size: "{{ templates.alma9.storage.size }}"
      vm_name: "{{ code.glab.name[iteration] }}"
      vm_id: "{{ code.glab.id[iteration] }}"
      vm_description: "{{ code.glab.description[iteration] }}"
      vm_storage: "{{ code.glab.storage }}"
      vm_storage_size: "{{ code.glab.size }}"
      vm_sockets: "{{ code.glab.sockets }}"
      vm_cores: "{{ code.glab.cores }}"
      vm_mem: "{{ code.glab.mem }}"
      vm_vid: "{{ code.glab.vid }}"
      ## To configure the service, see playbooks/code.yml

  - name: create Code/Runner subsystem VMs
    tags: ["vms","services","code","gitlab","services/gitlab","gitlab/runner"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","services","code","gitlab","services/gitlab","gitlab/runner"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(code.runr.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating Code VM on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.alma9.name }}"
      template_id: "{{ templates.alma9.id }}"
      template_storage: "{{ templates.alma9.storage.type }}"
      template_storage_size: "{{ templates.alma9.storage.size }}"
      vm_name: "{{ code.runr.name[iteration] }}"
      vm_id: "{{ code.runr.id[iteration] }}"
      vm_description: "{{ code.runr.description[iteration] }}"
      vm_storage: "{{ code.runr.storage }}"
      vm_storage_size: "{{ code.runr.size }}"
      vm_sockets: "{{ code.runr.sockets }}"
      vm_cores: "{{ code.runr.cores }}"
      vm_mem: "{{ code.runr.mem }}"
      vm_vid: "{{ code.runr.vid }}"
      ## To configure the service, see playbooks/code.yml

  - name: create k8s/control subsystem
    tags: ["vms","infrastructure","k8s","control","infrastructure/k8s","k8s/control"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","infrastructure","k8s","control","infrastructure/k8s","k8s/control"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(talos.control_plane.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating K8S Control Plane VM on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      vm_name: "{{ talos.control_plane.name[iteration] }}"
      vm_id: "{{ talos.control_plane.id[iteration] }}"
      vm_description: "{{ talos.control_plane.description[iteration] }}"
      vm_storage: "{{ talos.control_plane.storage }}"
      vm_storage_size: "{{ talos.control_plane.size }}"
      vm_sockets: "{{ talos.control_plane.sockets }}"
      vm_cores: "{{ talos.control_plane.cores }}"
      vm_mem: "{{ talos.control_plane.mem }}"
      vm_vid: "{{ talos.control_plane.vid }}"
      vm_iso:  "{{ talos.control_plane.iso }}"
      vm_start: true
      vm_bios: "{{ talos.control_plane.bios }}"
      vm_cpu_type: "{{ talos.control_plane.cpu_type }}"
      ## To configure the service, see playbooks/kubernetes.yml

  - name: precompute servers
    tags: ["vms","infrastructure","k8s","data","infrastructure/k8s","k8s/data"]
    ansible.builtin.set_fact:
      servers: "{{ groups['compute_nodes'] | sort | list }}"
      num_compute_nodes: "{{ groups['compute_nodes'] | length }}"

  - name: create k8s/data subsystem
    tags: ["vms","infrastructure","k8s","data","infrastructure/k8s","k8s/data"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","infrastructure","k8s","data","infrastructure/k8s","k8s/data"]
    loop: "{{ range(talos.data_plane.name | length) | list }}"
    loop_control:
      loop_var: idx
      label: "Creating K8S Data Plane VM on {{ servers[idx % num_compute_nodes] }}"
    vars:
      hypervisor_target: "{{ servers[idx % num_compute_nodes] }}"
      vm_name: "{{ talos.data_plane.name[idx] }}"
      vm_id: "{{ talos.data_plane.id[idx] }}"
      vm_description: "{{ talos.data_plane.description[idx] }}"
      vm_storage: "{{ talos.data_plane.storage }}"
      vm_storage_size: "{{ talos.data_plane.size }}"
      vm_sockets: "{{ talos.data_plane.sockets }}"
      vm_cores: "{{ talos.data_plane.cores }}"
      vm_mem: "{{ talos.data_plane.mem }}"
      vm_vid: "{{ talos.data_plane.vid }}"
      vm_iso:  "{{ talos.data_plane.iso }}"
      vm_start: true
      vm_bios: "{{ talos.data_plane.bios }}"
      vm_cpu_type: "{{ talos.data_plane.cpu_type }}"
      ## To configure the service, see playbooks/kubernetes.yml

  - name: create temporary storage controller
    tags: ['vms','services','storage']
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ['vms','services','storage']
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(storage.tnas.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating TrueNAS VM on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      vm_name: "{{ storage.tnas.name[iteration] }}"
      vm_id: "{{ storage.tnas.id[iteration] }}"
      vm_description: "{{ storage.tnas.description[iteration] }}"
      vm_storage: "{{ storage.tnas.storage }}"
      vm_storage_size: "{{ storage.tnas.size }}"
      vm_storage_cache: "{{ storage.tnas.cache }}"
      vm_sockets: "{{ storage.tnas.sockets }}"
      vm_cores: "{{ storage.tnas.cores }}"
      vm_mem: "{{ storage.tnas.mem }}"
      vm_vid: "{{ storage.tnas.vid }}"
      vm_start: true
      ## To configure the service, see playbooks/code.yml

  - name: create Code/Runner subsystem VMs
    tags: ["vms","services","analysis","syslog","analysis/syslog"]
    run_once: true
    ansible.builtin.include_role:
      name: portable/vm
      apply:
        tags: ["vms","services","analysis","syslog","analysis/syslog"]
    loop: "{{ (groups['compute_nodes'] | sort | list)[0:(analysis.syslog.name | length)] }}"
    loop_control:
      loop_var: server
      index_var: iteration
      label: "Creating Code VM on {{ server }}"
    vars:
      hypervisor_target: "{{ server }}"
      template_name: "{{ templates.alma9.name }}"
      template_id: "{{ templates.alma9.id }}"
      template_storage: "{{ templates.alma9.storage.type }}"
      template_storage_size: "{{ analysis.syslog.size }}"
      vm_name: "{{ analysis.syslog.name[iteration] }}"
      vm_id: "{{ analysis.syslog.id[iteration] }}"
      vm_description: "{{ analysis.syslog.description[iteration] }}"
      vm_sockets: "{{ analysis.syslog.sockets }}"
      vm_cores: "{{ analysis.syslog.cores }}"
      vm_mem: "{{ analysis.syslog.mem }}"
      vm_vid: "{{ analysis.syslog.vid }}"
      vm_start: true
