- hosts: git
  gather_facts: false

  tasks:
# Apply Linux baseline
  - name: configure ssh
    tags: ["baseline","ssh"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux.yml


# Configure gitstrap service
  - name: configure gitstrap
    tags: ["gitstrap","git"]
    ansible.builtin.import_role:
      name: services/git
      tasks_from: gitstrap.yml
