# Configures the centralized identity manager
- name: configure enterprise wide domain
  hosts: identity_authority
  gather_facts: false

  pre_tasks:
  - name: load site vars
    tags: ["always"]
    ansible.builtin.include_vars:
      file: "../inventories/{{ inventory_type }}/{{ site }}/group_vars/rwdc.yml"

  - name: load creds
    ansible.builtin.set_fact:
      ansible_user: "{{ accounts[2].username }}"
      ansible_password: "{{ credentials[accounts[2].username] }}"
    no_log: true
    run_once: true
    tags: ["always"]

  - name: check connection
    ansible.builtin.win_ping:
    tags: ["always"]

  tasks:
  - name: configure ou tree
    ansible.builtin.import_role:
      name: services/identity
      tasks_from: ou.yml
    tags: ["ou"]

  - name: configure sites and subnets
    ansible.builtin.import_role:
      name: services/identity
      tasks_from: sites_subnets.yml
    tags: ["sites"]

  - name: configure groups
    ansible.builtin.import_role:
      name: services/identity
      tasks_from: groups.yml
    tags: ["groups"]

  - name: configure ansible service accounts
    ansible.builtin.import_role:
      name: services/identity
      tasks_from: svc-accounts.yml
    tags: ["svc","accounts"]
