# Applies all Policy components to the identity authority
- name: Apply Policy Components
  hosts: identity_authority
  gather_facts: false

  pre_tasks:
  - name: load site vars
    tags: ["always"]
    ansible.builtin.include_vars:
      file: "../inventories/{{ inventory_type }}/{{ site }}/group_vars/rwdc.yml"

  - name: load creds
    ansible.builtin.set_fact:
      ansible_user: "{{ accounts[2].username }}"
      ansible_password: "{{ credentials[accounts[2].username] }}"
    no_log: true
    run_once: true
    tags: ["always"]

  - name: check connection
    ansible.builtin.win_ping:
    tags: ["always"]

  tasks:
  - name: apply GPOs
    tags: ["gpo"]
    ansible.builtin.import_role:
      name: policy/gpo
      tasks_from: main.yml
