# Configure the Splunk Service
## All commands are executed via API calls, so the playbook targets the localhost to avoid constant delegate_to

- name: configure splunk service
  hosts: localhost
  gather_facts: false

  pre_tasks:
  - name: get talosctl version
    tags: ['always']
    ansible.builtin.command: talosctl version --client --short
    register: talosctl_version_raw
    failed_when: false
    changed_when: false

  - name: parse talosctl
    tags: ['always']
    ansible.builtin.set_fact:
      parsed: "Talos v{{ versions.talos }}"

  - name: ensure talosctl matches pinned version
    tags: ['always']
    ansible.builtin.assert:
      that:
      - talosctl_version_raw.stdout_lines[1] == parsed

  - name: load pod name
    tags: ['always']
    ansible.builtin.import_role:
      name: services/data
      tasks_from: prep.yml

  tasks:
  - name: configure indexes
    tags: ['indexes']
    ansible.builtin.import_role:
      name: services/data
      tasks_from: render.yml
    vars:
      config: indexes

  - name: configure inputs
    tags: ['inputs']
    ansible.builtin.import_role:
      name: services/data
      tasks_from: render.yml
    vars:
      config: inputs

  - name: configure props
    tags: ['props']
    ansible.builtin.import_role:
      name: services/data
      tasks_from: render.yml
    vars:
      config: props