- hosts: vfws
  gather_facts: false

  pre_tasks:
  - name: probe for connection status
    tags: ['always']
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux_check.yml

  tasks:

# Baseline
  - name: Configure SSH
    tags: ["baseline","ssh"]
    ansible.builtin.import_role:
      name: portable/ssh
      tasks_from: linux.yml

  - name: apply linux baseline
    tags: ["baseline","host"]
    ansible.builtin.import_role:
      name: portable/baseline
      tasks_from: linux.yml

# Service Config
  - name: run prep tasks
    tags: ["always","prep"]
    ansible.builtin.import_role:
      name: infrastructure/vfws
      tasks_from: prep.yml

  - name: apply interface configs
    tags: ["service","vfw","ints"]
    ansible.builtin.import_role:
      name: infrastructure/vfws
      tasks_from: interfaces.yml

  - name: apply nftables configs
    tags: ["service","vfw","nft"]
    ansible.builtin.import_role:
      name: infrastructure/vfws
      tasks_from: nftables.yml

  - name: apply keepalived configs
    tags: ["service","vfw","keepalive"]
    ansible.builtin.import_role:
      name: infrastructure/vfws
      tasks_from: keepalived.yml


