# Called from the baseline role to configure the network settings on the bootstrap node

- name: Grab Interface Name
  ansible.builtin.shell: find /sys/class/net -type l -not -lname "*virtual*" -printf "%f"
  register: physical_iface_name
  changed_when: false

- name: set bridges with IPs
  loop: "{{ bridges }}"
  when: "'ip' in item"
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED: portable > baseline > proxmox_network > {{ item.name }}"
    path: /etc/network/interfaces
    block: |
      auto vmbr{{ item.vlan.id }}
      iface vmbr{{ item.vlan.id }} inet static
        address {{ item.ip }}
        gateway {{ item.gateway }}
        bridge-ports {{ physical_iface_name.stdout }}.{{ item.vlan.id }}
        bridge-stp off
        bridge-fd 0
  notify: Reload interface configurations

- name: set bridges without IPs
  loop: "{{ bridges }}"
  when: "'ip' not in item"
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    marker: "# {mark} ANSIBLE MANAGED: portable > baseline > proxmox_network > {{ item.name }}"
    block: |
      auto vmbr{{ item.vlan.id }}
      iface vmbr{{ item.vlan.id }} inet manual
        bridge-ports {{ physical_iface_name.stdout }}.{{ item.vlan.id }}
        bridge-stp off
        bridge-fd 0
  notify: Reload interface configurations
