# Baseline configurations

- name: set pfsense hostname
  become: true
  pfsensible.core.pfsense_setup:
    hostname: "{{ inventory_hostname }}"
    domain: "{{ domain.sub }}.{{ domain.root }}"
  changed_when: false

- name: set freebsd hostname
  become: true
  ansible.builtin.command: "hostname {{ inventory_hostname }}.{{ domain.sub }}.{{ domain.root }}"
  changed_when: false

- name: set time and ntp
  become: true
  pfsensible.core.pfsense_setup:
    timezone: "America/New_York"
    timeservers: "{{ dcs.rodc.hostname }}"
  changed_when: false

- name: set dns
  become: true
  pfsensible.core.pfsense_setup:
    dns_addresses: "{{ dcs.rodc.ip }}"
    dnsallowoverride: false
    dnslocalhost: false
  changed_when: false

# TODO: configure DNSSEC

- name: install wireguard package
  become: true
  ansible.builtin.package:
    name: pfSense-pkg-WireGuard
    state: present

- name: install syslog-ng package
  become: true
  ansible.builtin.package:
    name: pfSense-pkg-syslog-ng
    state: present

- name: configure system logging  
  become: true
  pfsensible.core.pfsense_log_settings:
    logformat: "rfc5424"
    nologbogons: true
    nologdefaultblock: true
    nologlinklocal4: true
    nologprivatenets: true
