# Applies baseline configuration for the C1200 access switch
## C1200s dont present configs the way cisco.ios.ios_config expects them, so in many cases they don't report changes correctly
## changed_when: false is used to clean up the output on unimportant or always changing config lines
- name: disable energy efficient ethernet
  become: true
  cisco.ios.ios_config:
    lines:
    - no eee enable
    save_when: changed

- name: apply hostname
  become: true
  cisco.ios.ios_config:
    lines:
    - "hostname {{ inventory_hostname }}"
    save_when: changed

- name: clear domain name
  become: true
  cisco.ios.ios_config:
    lines:
    - no ip domain name
  changed_when: false

- name: apply domain name
  become: true
  cisco.ios.ios_config:
    lines: # have to clear the domain name first
    - "ip domain name {{ domain.sub }}.{{ domain.root }}"
    save_when: changed
  changed_when: false

## Set Clock Settings
### Have to extend the timeout for these; internal recalculation will often cause a first-run fail
- name: set standard timezone
  become: true
  cisco.ios.ios_config:
    lines:
    - "clock timezone {{ timezone.standard.acronym }} {{ timezone.standard.hrs_diff }}"
    save_when: changed
  vars:
    ansible_command_timeout: 120

- name: set daylight savings timezone
  become: true
  when: "timezone.daylight is defined"
  cisco.ios.ios_config:
    lines:
    - "clock summer-time {{ timezone.daylight.acronym }} recurring usa {{ timezone.daylight.mins_diff }}"
    save_when: changed
  vars:
    ansible_command_timeout: 120


- name: set clock to ntp source
  become: true
  cisco.ios.ios_config:
    lines:
    - clock source sntp
    save_when: changed

- name: set ntp sources
  become: true
  cisco.ios.ios_config:
    lines:
    - "sntp server {{ item.value.ip }}"
    save_when: changed
  loop: "{{ dcs | dict2items }}"

