# Configures interfaces on the Cisco SMB Switches (C1200)
## DEV NOTE: C1200s don't present configs the same way cisco.ios.ios_config expects
### changed_when: false is used to clean up the output to focus on end-state changes
- name: set access ports
  become: true
  loop: "{{ ifaces }}"
  loop_control:
    index_var: index
  cisco.ios.ios_config:
    lines:
    - "description \"{{ item.description }}\""
    - "switchport access vlan {{ item.access.vlan_id }}"
    - "{{ item.status }}"
    parents:
    - "interface {{ iface_prefix }} {{ index+1 }}"
    save_when: changed
  when: item.access is defined

- name: set trunk ports (w/out native vlans)
  become: true
  loop: "{{ ifaces }}"
  loop_control:
    index_var: index
  cisco.ios.ios_config:
    lines:
    - "description \"{{ item.description }}\""
    - "switchport trunk allowed vlan {{ item.trunk.vlan_ids }}"
    - "{{ item.status }}"
    parents:
    - "interface {{ iface_prefix }} {{ index+1 }}"
    save_when: changed
  when:
  - item.trunk is defined
  - item.trunk.native is not defined

- name: set trunk ports (w/ native vlans)
  become: true
  loop: "{{ ifaces }}"
  loop_control:
    index_var: index
  cisco.ios.ios_config:
    lines:
    - "description \"{{ item.description }}\""
    - "switchport trunk allowed vlan {{ item.trunk.vlan_ids }}"
    - "{{ item.status }}"
    parents:
    - "interface {{ iface_prefix }} {{ index+1 }}"
    save_when: changed
  when:
  - item.trunk is defined
  - item.trunk.native is defined

- name: shut disabled ports
  become: true
  loop: "{{ ifaces }}"
  loop_control:
    index_var: index
  cisco.ios.ios_config:
    lines:
    - "description {{ item.description }}"
    - "{{ item.status }}"
    parents:
    - "interface {{ iface_prefix }} {{ index+1 }}"
    save_when: changed
  when:
  - item.trunk is undefined
  - item.access is undefined
