# Required Ansible collections
## Each collection will include a reference to the role or playbook that requires it

collections:
# Added by the portable/ssh role
- name: ansible.posix
# Added by the core site core switch
- name: junipernetworks.junos
# Added by the portable/ssh role
- name: ansible.utils
# Added by the portable/vm role
- name: community.proxmox
