# Configures the gitstrap service on the bootstrap node
## A lightweight, Git-Over-SSH implementation as a hot-backup to the primary GitLab instance

# Overall Approach:
## Download and/or update the git package
## Configure git user
## Configure data disk
## Configure pre-receive hook for git
## Create bare IaC repo (if nonexistent)

# Download git package
- name: download git
  become: true
  ansible.builtin.package:
    name: git
    state: present

# Configure git user
- name: create git user
  become: true
  ansible.builtin.user:
    name: git
    shell: /usr/bin/git-shell
    state: present

# Configure data disk
- name: configure data disk
  ansible.builtin.import_role:
    name: portable/disks
    tasks_from: linux.yml

# Configure pre-receive hook for git
- name: 

# Create bare IaC repo
