# Creates and links GPOs
- name: create GPOs
  loop: "{{ gpos }}"
  loop_control:
    label: "Creating GPO {{ item.name }}"
  ansible.windows.win_powershell:
    script: |
      # Create the GPO
      New-GPO -Name {{ item.name }}
      # Stamp GPO to say it applies Computer policies
      if (${{ item.machine | default(false) | lower }})
      {
        Set-GPRegistryValue -Name {{ item.name }} -Key "HKLM\Software\_GPOBooststrap" -ValueName "Init" -Type DWORD -Value 1 | Out-Null
      }
      # Stamp GPO to say it applies User policies
      if (${{ item.user | default(false) | lower }})
      {
        Set-GPRegistryValues -Name {{ item.name }} -Key "HKCU\Software\_GPOBootstrap" -ValueName "Init" -Type DWORD -Value 1 | Out-Null
      }
  register: output
  changed_when: (output.output | default([]) | length) > 0

- name: link GPOs
  loop: "{{ gpos }}"
  loop_control:
    label: "Linking GPO {{ item.name }} to {{ item.ou }}"
  ansible.windows.win_powershell:
    script: "New-GPLink -Name {{ item.name }} -Target '{{ item.ou }}' -LinkEnabled Yes"
  register: output
  changed_when: (output.output | default([]) | length) > 0

- name: load site vars for data_drive
  ansible.builtin.include_vars:
    file: "../inventories/{{ inventory_type }}/{{ site }}/group_vars/all/all.yml"
  no_log: true

- name: configure GPOs
  loop: "{{ gpos }}"
  loop_control:
    label: "Configuring GPO {{ item.name }}"
  ansible.windows.win_powershell:
    script: |
      $changes = @()
      $domain = (Get-ADDomain).DNSRoot
      $gpo = Get-GPO -Name "{{ item.name }}"
      $gptPath = "{{ data_drive.letter }}:\AD\SYSVOL\sysvol\$domain\Policies\{$($gpo.Id)}\Machine\Microsoft\Windows NT\SecEdit"
      $infFile = Join-Path $gptPath "GptTmpl.inf"
      $backup = Join-Path $gptPath "GptTmpl.txt"
      $changed = $false

      ## Configure Restricted Groups
      $rg_desired = @'
      {{ lookup('template','gpo_restricted-groups.j2') }}
      '@
      $rg_desired = ($rg_desired -replace '\r\n',"`n").Trim()

      if (Test-Path $infFile) {
        $current = ((Get-Content $infFile -Raw) -replace '\r\n',"`n").Trim()
      }
      else
      {
        $current = ""
        New-Item -ItemType Directory -Path $gptPath -Force | Out-Null
      }

      if ($current.Length -ne 0)
      {
        if ($rg_desired -ne "None")
        {
          # if the file isn't empty
          # configure restricted groups
          $regex = '{{ (item.settings.restricted_groups | default({})).regex | default(omit) }}'
          if ($current -match $regex)
          {
            $rg_existingSection = [regex]::Match($current,$regex).Value.Trim()
            if ($rg_existingSection -ne $rg_desired)
            {
              # the restricted groups section doesnt match what we want
              # string to search within, regex to search for, content to put in
              $newContent = [regex]::Replace(
                $current,
                $regex,
                $rg_desired
              )
              $changes += "Fixed Restricted Groups Section"
              $changed = $true
            }
          }
          else
          {
            #the section doesnt exist
            $newContent = "$current`n`n$rg_desired"
            $changes += "Created Restricted Groups Section"
            $changed = $true
          }
        }
      }
      else
      {
        #file doesnt exist or is empty, create a minimal skeleton
        if ($rg_desired -eq "None") { $rg_desired = "" }
        $newContent = @"
      [Unicode]
      Unicode=yes

      [Version]
      signature=`"`$CHICAGO$`"

      $rg_desired
      "@
        $changes += "Created GptTmpl.inf"
        $changed = $true
      }

      if ($newContent) { $current = $newContent }

      ## Configure Privilege Rights
      # Resolve spec to SIDs
      $int_spec = @'
      {{ (item.settings.privilege_rights | default({})).interactive | default([]) | to_json }}
      '@ | ConvertFrom-Json
      $int_sids = @()
      foreach ($name in $int_spec)
      {
        $group = Get-ADGroup -Identity $name
        $int_sids += $group.SID
      }
      $remote_int_spec = @'
      {{ (item.settings.privilege_rights | default({})).remote_interactive | default([]) | to_json }}
      '@ | ConvertFrom-Json
      $remote_int_sids = @()
      foreach ($name in $remote_int_spec)
      {
        $group = Get-ADGroup -Identity $name
        $remote_int_sids += $group.SID
      }
      $net_spec = @'
      {{ (item.settings.privilege_rights | default({})).network | default([]) | to_json }}
      '@ | ConvertFrom-Json
      $net_sids = @()
      foreach ($name in $net_spec)
      {
        $group = Get-ADGroup -Identity $name
        $net_sids += $group.SID
      }
      # Create desired config
      $desired = @("[Privilege Rights]")
      if ($int_sids.Length -gt 0) { $desired += "SeInteractiveLogonRight=*$($int_sids -join ',*')" }
      if ($remote_int_sids.Length -gt 0) { $desired += "SeRemoteInteractiveLogonRight=*$($remote_int_sids -join ',*')" }
      if ($net_sids.Length -gt 0) { $desired += "SeNetworkLogonRight=*$($net_sids -join ',*')" }
      $pr_desired = $desired -join "`n"
      # compare to existing
      $regex = '{{ (item.settings.privilege_rights | default({})).regex | default(omit) }}'
      if ($current -match $regex)
      {
        # There already is a block for Privilege Rights
        $pr_existingSection = [regex]::Match($current,$regex).Value.Trim()
        if ($pr_existingSection -ne $pr_desired)
        {
          # the existing section doesnt match what we want
          $newContent = [regex]::Replace($current,$regex,$pr_desired)
          $changes += "Fixed Privilege Rights Section"
          $changed = $true
        }
      }
      else
      {
        # section doesnt exist
        $newContent = "$current`n`n$pr_desired"
        $changes += "Created Privilege Rights Section"
        $changed = $true
      }
      if ($newContent) { $current = $newContent }

      ## Event Log Settings
      $regex = "{{ (item.settings.event_log | default({})).regex | default(omit) }}"
      $settings = @'
      {{ item.settings.event_log.settings | to_nice_json }}
      '@ | ConvertFrom-Json
      $el_desired = @("[Event Log]")
      foreach ($log in $settings)
      {
        $log_name = $log.name
        foreach ($setting in $log.settings)
        {
          $el_desired += "$log_name__$($setting.name)=$($setting.value)"
        }
      }
      $el_desired = $el_desired -join "`n"
      if ($current -match $regex)
      {
        # theres already an event log block
        $el_existing = [regex]::Match($current,$regex).Value.Trim()
        if ($el_existing -ne $el_desired)
        {
          # exising section doesnt match what we want
          $newContent = [regex]::Replace($current,$regex,$el_desired)
          $changes += "Fixed Event Log Section"
          $changed = $true
        }
      }
      else
      {
        # section doesnt exist
        $newContent = "$current`n`n$el_desired"
        $changes += "Created Event Log Section"
        $changed = $true
      }
      if ($newContent) { $current = $newContent }

      ## Write Output
      if ($changed)
      {
        Copy-Item -Path $gptPath -Destination $backup -Force
        Set-Content -Path $infFile -Value $newContent -Encoding ASCII
      }

      ## Configure permissions for this GPO
      $permissions = @'
      {{ item.permissions | default([]) | to_json }}
      '@ | ConvertFrom-JSON
      foreach ($perm_spec in $permissions)
      {
        # get current permissions
        $perms = (Get-GPPermission "{{ item.name }}" -TargetName $perm_spec.identity -TargetType $perm_spec.type -ErrorAction SilentlyContinue | Sort-Object).Permission -join ","
        $p_desired = $perm_spec.perms -join ","
        if ($perms -ne $p_desired)
        {
          # if the existing doesnt match our desired state, we need to set it
          ## start by clearing all permissions for this principal
          try {
            Set-GPPermission "{{ item.name }}" -TargetName $perm_spec.identity -TargetType $perm_spec.type -PermissionLevel None -Replace | Out-Null
          } catch {
            $dnroot = (Get-ADDomain).DistinguishedName
            dsacls "CN={$($gpo.Id)},CN=Policies,CN=System,$dnroot" /R $($perm_spec.identity)
          }
          foreach ($p in $perm_spec.perms)
          {
            Set-GPPermission "{{ item.name }}" -TargetName $perm_spec.identity -TargetType $perm_spec.type -PermissionLevel $p | Out-Null
            $changes += "Set permission for $($perm_spec.identity) on {{ item.name }} to $p"
          }
          $changed = $true
        }
      }

      ## Increment GPO Version if updates were made
      if ($changed)
      {
        $path = "{{ data_drive.letter }}:\AD\SYSVOL\sysvol\{{ domain_name }}\Policies\{$($gpo.Id)}\gpt.ini"
        $content = Get-Content $path -ErrorAction SilentlyContinue -Raw
        if ( -not $content)
        {
          $content = @("[General]","Version=65536") -join "`r`n"
        }
        else
        {
          $version = [regex]::Match($content,'Version=(\d+)').Groups[1].Value.Trim()
          $newVersion = "Version=$([int]$version + 65536)"
          $content = [regex]::Replace($content,"Version=\d+",$newVersion)
        }
        Set-Content -Path $path -Value $content -Encoding ASCII
        $changes += "Updated GPO Version"
      }

      ## Return changed status
      @{ changed = $changed; changes = $changes }
  register: output
  changed_when: output.output[0].changed

- name: show changes
  when: output.results[0].output[0].changed
  debug:
    var: output.results[0].output[0].changes
